openapi: 3.0.1
info:
  title: dapr
  version: '1.0'
  description: API for demonstrating Dapr integration policies in Azure API Management
  contact:
      email: vlvinogr@microsoft.com
servers:
  - url: http://one.azure-api.net
paths:
  /echo:
    post:
      summary: Invoke service
      description: Invoke service
      operationId: invoke-service
      requestBody:
        content:
          application/json:
            example:
              message: hello
      responses:
        '200':
          description: ''
      tags:
          - dapr-invoke
  /message:
    post:
      summary: Send message to topic
      description: Send message to PubSub topic
      operationId: send-message
      requestBody:
        content:
          application/json:
            example:
              content: hello
      responses:
        '200':
          description: ''
      tags:
          - dapr-pubsub
  /save:
    post:
      summary: Store data in storage
      description: Use outbound binding to persist data
      operationId: store-data
      requestBody:
        content:
          application/json:
            example:
              city: PDX,
              time: 1600171062
              metric: aqi
              value: 457
      responses:
        '200':
          description: ''
      tags:
          - dapr-binding
tags:
    - name: dapr-invoke
    - name: dapr-pubsub
    - name: dapr-binding